version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "admin-restaurant-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=restaurant
      - POSTGRES_PASSWORD=restaurant
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "admin-restaurant-rest-api"
    environment:
      DB_USERNAME: "restaurant"
      DB_PASSWORD: "restaurant"
      DB_DB: "restaurant"
      DB_HOST: "db"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge

