DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS channel;
DROP TABLE IF EXISTS corporaiton;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS course_on_menu;
DROP TABLE IF EXISTS desk;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS order;
